### ISSUE TITLE
cannot use time.Unix as type int64 in argument to tsm1.NewValue

### ISSUE THREAD

**Issue by Infiniverse** [influxdata/whisper-migrator#14]
The whisper migrator doesn't appear to run on my FreeBSD system

```
# env GOPATH=`pwd` go get github.com/influxdata/whisper-migrator
# env GOPATH=`pwd` go run src/github.com/influxdata/whisper-migrator/migration.go
# command-line-arguments
src/github.com/influxdata/whisper-migrator/migration.go:474: cannot use time.Unix(int64(wspPoint.Timestamp), 0) (type time.Time) as type int64 in argument to tsm1.NewValue
```

**Comment by Infiniverse** [comment]
Hello, does anyone have any ideas about this? Look like it ought to be a simple fix.

**Comment by Infiniverse** [comment]
Not sure where to start looking for a solution. I don't know the 'go' language yet, so I'm a bit in the dark.

**Comment by Infiniverse** [comment]
I forgot to mention, I'm running with with go 1.6:

```
[root@europa /home/joe/whisper-migrator]# go version  
go version go1.6 freebsd/amd64

```

**Comment by uttamgandhi** [comment]
Thanks for reporting the issue.
I am getting the same error, after updating the latest code of influxdata/influxdb. I think I will have to change the usage of NewValue, will update you soon

**Comment by Infiniverse** [comment]
Cool - I didn’t think that it was me! :)

Cheers,
Joe

**Comment by uttamgandhi** [comment]
I have raised a pull request, https://github.com/influxdata/whisper-migrator/pull/15, which fixes the issue. Thanks again for reporting this issue

**Comment by Infiniverse** [comment]
Thanks :).

**Comment by Infiniverse** [comment]
Yes, that works now with that fix. Cheers.
