### ISSUE TITLE
Detection of malformed json

### ISSUE THREAD

**Issue by olref** [influxdata/whisper-migrator#5]
When the migration_config.json file is not valid (for example you add a comma at a wrong place ;-) )
there are no warning from the tool.

Example of a file that caused me a problem (it took me some minutes to find why migrator doesn't understand my pattern) :

```
[
  {
    "pattern": "TEST.2013.#TEXT1.#TEXT2",
    "measurement": "#TEXT2",
    "tags": [
      {
        "tagkey": "host",
        "tagvalue": "#TEXT1"
      }
    ],
    "field": "value"
  },
]
```

It could be a great help, if the migration tool return a warning when it can't parse the json.

Perhaps is it possible to get error returned by json.Unmarshal and display it as a warning (into the function ReadTagConfig)

```
err = json.Unmarshal(raw, &migrationData.tagConfigs)
if err != nil {
  fmt.Printf("Can not parse migration_config.json : %s", err)
}
```

Thanks for this tool, it will be very useful !

**Comment by uttamgandhi** [comment]
Thanks for identifying this issue.

I have created a pull request, to handle this request
https://github.com/influxdata/whisper-migrator/pull/8

If you are keen to have a look you take the feature branch
